### ISSUE TITLE
Unknown sensor

### ISSUE THREAD

**Issue by dkNeumann** [basschipper/homeassistant-generic-hygrostat#45] opened 2023-03-09 16:14 UTC
Hi,
Just installed the hygrostat using my Multisensor 6 from AEOTEC (z-wave), and the following error shows up:

Logger: custom_components.generic_hygrostat.binary_sensor
Source: custom_components/generic_hygrostat/binary_sensor.py:85
Integration: generic_hygrostat (documentation)
First occurred: 17.08.03 (1 occurrences)
Last logged: 17.08.03
Unknown humidity sensor 'sensor.bathroom_sensor_humidity'

My config is:
  - platform: generic_hygrostat
    name: Bathroom Hygrostat
    sensor: sensor.bathroom_sensor_humidity
    #attribute:  # Optional use sensor attribute instead of state.
    delta_trigger: 3 # Optional humidity swing to detect. Default = 3
    target_offset: 3 # Optional dehumidification target offset. Default = 3
    min_on_time: 300 # Optional min on time in seconds. Default = 0 seconds
    max_on_time: 7200 # Optional safety max on time in seconds. Default = 7200 seconds
    sample_interval: 300 # Optional time between taking humidity samples in seconds, default 300 seconds
    min_humidity: 30 # Optional minimum humidity to enable dehumidification. Default = 0
    unique_id: bathroom_hygrostat 

(this is in my configuration.yaml)

**Comment by Corsw** [comment] 2023-03-17 13:51
Unfortunately i'm facing the same issue. This is the error in the log:

```
Logger: custom_components.generic_hygrostat.binary_sensor
Source: custom_components/generic_hygrostat/binary_sensor.py:85
Integration: generic_hygrostat ([documentation](https://github.com/basschipper/homeassistant-generic-hygrostat))
First occurred: 14:42:41 (1 occurrences)
Last logged: 14:42:41

Unknown humidity sensor 'sensor.badkamer_aqara_humidity'
```

The sensor is working, and showing like this in HA:

```
state_class: measurement
unit_of_measurement: '%'
device_class: humidity
friendly_name: Luchtvochtigheid badkamer (aqara)
```

And this is how its configured in my configuration.yaml:

```
  - platform: generic_hygrostat
    name: Badkamer hygrostaat
    sensor: sensor.badkamer_aqara_humidity 
    delta_trigger: 3 
    target_offset: 3 
    sample_interval: 30 
    min_humidity: 30 
    unique_id: badkamer_hygrostaat 
```

Any idea whats going wrong here?

**Comment by basschipper** [comment] 2023-06-08 05:35
Duplicate of #30

**Closed as completed by basschipper** 2023-06-08 05:35 UTC
