### ISSUE TITLE
Can u remove this warning please

### ISSUE THREAD

**Issue by hellcry37** [basschipper/homeassistant-generic-hygrostat#44] opened 2023-03-07 09:57 UTC
Hello

For all intents and purposes your integration work great for me, thank you!

The only issue that I encounter with it is in the log of home assistant after every home assistant restart.

`2023-03-07 10:13:38.683 WARNING (MainThread) [custom_components.generic_hygrostat.binary_sensor] Unable to update humidity from sensor 'sensor.bathroom_humidity' with value 'unavailable'`

Note that sensor.bathroom_humidity is a group sensor that has 2 zigbee sensors in it (median value)

**Comment by basschipper** [comment] 2023-06-08 05:39
Duplicate of #30

**Closed as completed by basschipper** 2023-06-08 05:39 UTC
