### ISSUE TITLE
Latest update broke generic hygrostat 

### ISSUE THREAD

**Issue by Dutchy-79** [basschipper/homeassistant-generic-hygrostat#48] opened 2023-06-08 04:38 UTC
Latest update from HA seems to break this integration.

Can only restart if I exclude the config in configuration.yaml

![Screenshot_20230608_063344_Home Assistant](https://github.com/basschipper/homeassistant-generic-hygrostat/assets/22749572/fc035531-96fd-4d2f-bfe3-e00ea3d03d35)

**Comment by basschipper** [comment] 2023-06-08 05:36
Duplicate of #46

**Closed as completed by basschipper** 2023-06-08 05:36 UTC
